[package]
name = "font-cache"
version = "0.1.0"
authors = ["Ryan Goldstein <ryan@ryanisaacg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.22", default-features = false, optional = true }
rusttype = { version = "0.8", optional = true }
unicode-normalization = { version = "0.1.12", optional = true }
